### ISSUE TITLE
Unable to compile on Archlinux

### ISSUE THREAD

**Issue by jiwilat** [utsushi/utsushi#16]
My mistake, found out that adding "AX_CXX_COMPILE_STDCXX_11()" to configure.ac solves the problem
++++
I've been trying to compile this package on Arch linux and I'm getting errors of this kind:

make[2]: Entering directory '/home/user/tmp/scanner/utsushi-master/gtkmm'
  CXX      action-dialog.lo
In file included from /usr/include/glibmm-2.4/glibmm/exception.h:25:0,
                 from /usr/include/glibmm-2.4/glibmm/error.h:23,
                 from /usr/include/glibmm-2.4/glibmm/thread.h:49,
                 from /usr/include/glibmm-2.4/glibmm.h:87,
                 from /usr/include/gtkmm-2.4/gtkmm/dialog.h:7,
                 from action-dialog.hpp:27,
                 from action-dialog.cpp:25:
/usr/include/glibmm-2.4/glibmm/ustring.h:267:3: error: identifier ‘noexcept’ is a keyword in C++11 [-Werror=c++0x-compat]
   ~ustring() noexcept;
   ^

**Comment by paddy-hack** [comment]
Alternatively, you can specify whatever `CXXFLAGS` are needed at configure time, like so (for `gcc`)

```
./configure CXXFLAGS="-std=c++11"
```

or at build time with

```
make CXXFLAGS="-std=c++11
```

**Comment by jiwilat** [comment]
Thank you very much Olaf, that's even easier than what I'm using right 
now which is a sed command that changes configure.ac 
file. I'm creating an AUR package for Arch Linux so 
this comes quite handy.

By the way, if you allow me I would like to take this opportunity and 
ask you a couple questions:
1. I'm using the official Utsushi package available at 
   http://support.epson.net, should I use the package available at Github 
   instead or is it considered "unstable"?
2. I saw that there are three patches with the official package 
   (gdk-pixbuf-format.patch, gtkmm-2.20-compat.patch and rebranding.patch) 
   are they mandatory for creation? (in fact I wasn't able to compile the 
   package if applied the gtkmm patch)

Thank you very much for your help, and please forgive me for taking away 
your time

**Comment by paddy-hack** [comment]
OK, first, for completeness' sake, about the C++11 issue.  Utsushi itself does not require C++11 yet.  It supports compilation with both C++03 and C++11.  It is just that other libraries that Utsushi depends on, like glibmm and/or libsigc++, may require C++11 depending on the distribution (and version thereof) that you build on.

As for which source to use, that's really up to you.  I have been tracking the upstream sources from the EPSON site in [imagescan](https://github.com/utsushi/imagescan) since the first release and merge these to this project.  As a matter of fact, I just added the `imagescan-3.15.0` sources :wink:.  If there is anything that I don't like about "upstream" or something someone wants added, it is more likely to get taken care of here.

With respect to the patches, Utsushi should build and work fine without them.  They mostly work around issues on older distributions.  The rebranding.patch is only cosmetic and changes Utsushi into "Image Scan v3".  If you drop it, it might be a good idea to have your package conflict with any `imagescan` package.  The rebranding.patch does not change a number of the installation paths.  Like I said, it's only cosmetic.
