### ISSUE TITLE
bootstrap fails with "It seems there is a new AX_BOOST_BASE macro version..."

### ISSUE THREAD

**Issue by pniederlag** [utsushi/utsushi#22]
executing ./bootstrap on debian testing/unstable does fail with:

```
autoreconf: libtoolize failed with exit status: 1
It seems there is a new AX_BOOST_BASE macro version out there.  The
local patching that follows has not been tested on this version, so
there may be trouble ahead.  If everything went fine for you please
update the serial number used for this check in ./bootstrap.
```

So I had a quick look at the source of the script and executing the check myself:

```
 awk '/^#serial/{ if ($2>25) print $2 }' upstream/aclocal/ax_boost_base.m4
```

I found it does give version 26 for me (on debian testing/unstable). Is this a distribution related value or a value that is set by the upstream imagescan source?

**Comment by paddy-hack** [comment]
It's an `ax_boost_base.m4` value.  The `utsushi` build gets that file from your system's currently installed version of the `autoconf-archive` package.  The check is merely to _warn_ about the fact that the patching of `ax_boost_base.m4` has not been tested on the version you have.  Can't test against stuff that didn't exist yet at the time of testing :wink:  Most of the time though, the changes will not break the patching.  I just checked the [changes between 25 and 26](http://git.savannah.gnu.org/cgit/autoconf-archive.git/commit/m4/ax_boost_base.m4?id=c283ca4f5d0a86a7ed997fce8ba9146697efc621) and you can safely bump the version number.  Matter of fact, I just did.  It's in 63dfb299a

However, I think your problem is more with

> autoreconf: libtoolize failed with exit status: 1

Is there any indication of what went wrong?  If not, try running

```
LIBTOOLIZE="libtoolize --verbose" ./bootstrap
```

and append the log.

**Comment by pniederlag** [comment]
Thx for your support/help. I put the information into a gist https://gist.github.com/pniederlag/e037fdf17ef185487ffbf08b5780ad89

What is the most failsafe bet on the include-boost thingy? 
Could you reenable the .travis building?

**Comment by paddy-hack** [comment]
> I put the information into a gist https://gist.github.com/pniederlag/e037fdf17ef185487ffbf08b5780ad89

Hmm, no idea why `libtoolize` would exit with an error.  I'm building a `debian/testing` container to have a look at this.

> What is the most failsafe bet on the include-boost thingy?

On Debian testing/unstable you should be able to use Debian's libboost packages.  There should be no need to use the "include-boost thingy".

> Could you reenable the .travis building?

I'd have to check first if they support builds that require about 2.5GB of RAM per core.  When I first played around with Travis-CI, the builds got killed because they were too memory hungry.

**Comment by paddy-hack** [comment]
> I'm building a debian/testing container to have a look at this.

My container is up-to-date with `testing` as of 2016-06-05.
The first `./bootstrap` in a clean checkout (or after a `git clean -X -d -f`) outputs the following near the end:

```
patching file upstream/ltmain.sh
Hunk #1 succeeded at 3827 with fuzz 1 (offset 1317 lines).
Hunk #2 succeeded at 5336 (offset 1375 lines).
Hunk #3 FAILED at 8180.
Hunk #4 FAILED at 8638.
2 out of 4 hunks FAILED -- saving rejects to file upstream/ltmain.sh.rej
```

That is something that needs to be addressed (see also #15) but it does _not_ cause `libtoolize` to fail for me.  What does fail is the _second_ `./bootstrap` because `libtoolize` refuses to overwrite existing files.  At first, I thought that that would _not_ result in an exit status of 1 but upon checking the `libtoolize` source (it's a shell script), I found that it does.

If you have `./bootstrap`ped before, run `./bootstrap --force`.  The `./bootstrap --help` mentions this option but does not indicate that you should use it when rerunning :cry: 
I'll push a documentation fix shortly.

**Comment by paddy-hack** [comment]
> >  Could you reenable the .travis building?
> 
> I'd have to check first if they support builds that require about 2.5GB of RAM per core. When I first played around with Travis-CI, the builds got killed because they were too memory hungry.

It looks like the Ubuntu Trusty [build environments](https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments) are powerful enough to run a two core build.  I'll give it a go (see 263f500).

**Comment by paddy-hack** [comment]
:sob: Trusty's `gettext` is too old.  I'll see if I can upgrade the `.travis.yml` file to use a container with the latests Ubuntu LTS (16.04) but it looks like I won't be able to use the `install-deps` script anymore then.

**Comment by paddy-hack** [comment]
FYI, I've cooked up something that [builds successfully](https://travis-ci.org/utsushi/utsushi/builds/136129341) on Travis-CI :smile:.

It bootstraps the checkout on Debian's `stable` and then continues to build on Ubuntu's `trusty` :scream:
