### ISSUE TITLE
The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.

### ISSUE THREAD

**Issue by ghost** [utsushi/utsushi#4]
Trying to compile on Debian Jessie, ./bootstrap gives me this:

> automake: warnings are treated as errors
> configure.ac:229: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
> configure.ac:229: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
> configure.ac:229: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
> autoreconf: automake failed with exit status: 1
> automake: warnings are treated as errors
> configure.ac:229: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
> configure.ac:229: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
> configure.ac:229: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
> automake: warnings are treated as errors
> configure.ac:229: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
> configure.ac:229: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
> configure.ac:229: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
> autoreconf: automake failed with exit status: 1
> automake: warnings are treated as errors
> configure.ac:229: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
> configure.ac:229: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
> configure.ac:229: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.

**Comment by paddy-hack** [comment]
Thanks for the report.  I've come across this myself and, for a long while, have been working around it with

```
AUTOMAKE=automake-1.11 ACLOCAL=aclocal-1.11 ./bootstrap
```

Of course, this requires that you install `automake1.11` on a Debian `jessie` system :disappointed:

The warning itself is caused by an `aclocal` macro that originates with `gettext`.  Bumping the required `gettext` version (in `configure.ac`) to that in `jessie` will fix this.  This is what I've been using locally for a while now and planned to push that once `jessie` becomes `stable`.  As that is supposed to happen in a couple of days I guess I might as well jump the gun and push a fix now.
